### ISSUE TITLE
Push notification URL

### ISSUE THREAD

**Issue by kudit** [passworks/android-wallet-api#1]
Why isn't the push notification URL /v1/pushUpdate like Apple and PassWallet?

**Comment by lmmendes** [comment]
Can you elaborate on that?

**Comment by kudit** [comment]
Your documentation states the push notification URL for your service is /v1/push

Apple's push URL is /v1/pushUpdate as is Attido's PassWallet API URL.

Just seems unnecessarily different.

**Comment by lmmendes** [comment]
Hi @kudit  

Just pushed to production an updated version of the API.

We now support the `/v1/pushUpdate` endpoint officially (for historic reasons we still support the `/v1/push` but it's no longer documented in our readme, please update when you can).

**Comment by kudit** [comment]
Thanks
